# Generated by Django 5.1.7 on 2025-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_start', models.DateField()),
                ('availability_end', models.DateField()),
                ('number_of_beds', models.IntegerField()),
                ('distance_to_hku', models.FloatField()),
            ],
        ),
    ]
